"""Add deposit method fields to Order

Revision ID: 85a23c922bc5
Revises: e2e314116bc0
Create Date: 2026-05-27 21:09:06.644351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a23c922bc5'
down_revision = 'e2e314116bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('deposit_bank', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('deposit_account_holder', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('deposit_transaction_reference', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('deposit_transaction_reference')
        batch_op.drop_column('deposit_account_holder')
        batch_op.drop_column('deposit_bank')
        batch_op.drop_column('deposit_method')

    # ### end Alembic commands ###
